#### general settings
name: 002_SRGANx2_MSRResNetx2Ini_batch6
use_tb_logger: true
model: srgan
distortion: sr
scale: 2
gpu_ids: [0, 1]

#### datasets
datasets:
  train:
    name: batch6
    mode: LQGT
    dataroot_GT: ../../datasets/super_resolution/batch6/HR_train
    dataroot_LQ: ../../datasets/super_resolution/batch6/LR_train/x2

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 16
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: val_fashion
    mode: LQGT
    dataroot_GT: ../../datasets/super_resolution/val_fashion/HR/x2
    dataroot_LQ: ../../datasets/super_resolution/val_fashion/LR/x2

#### network structures
network_G:
  which_model_G: MSRResNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 16
network_D:
  which_model_D: discriminator_vgg_128
  in_nc: 3
  nf: 64

#### path
path:
  pretrain_model_G: ../experiments/pretrained_models/MSRResNetx4.pth
  strict_load: false
  resume_state: ../experiments/002_SRGANx2_MSRResNetx2Ini_batch6/training_state/400000.state

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 1000000
  warmup_iter: -1  # no warm up
  lr_steps: [125000, 250000, 500000, 750000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: 1
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-3

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e4
